# If the PR has the label release:major, release:minor, or release:patch, this will override bump_version_scheme.
# https://github.com/marketplace/actions/release-tag-new-action
on: 
  push:
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.CHAIN_ACCESS_TOKEN }}
    steps:
      - id: release
        name: Release Tag
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v
